import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../outputs/interface-workshop-hero.html', import.meta.url), 'utf8');
const featuredWorkHeaderSvg = readFileSync(new URL('../featured-work-header-1.svg', import.meta.url), 'utf8');
const renderedText = html.replace(/<[^>]+>/g, ' ');

assert.match(html, /<nav[\s>]/, 'provides semantic navigation');
assert.match(html, /href="\.\.\/MANISH_CV\.pdf" download="Manish-Gaud-Resume\.pdf"/, 'provides a downloadable resume in the header');
assert.match(html, />Resume <span class="nav-cta__icon"/, 'labels the header CTA as Resume');
assert.match(renderedText, /I shape messy product ideas into\s+interfaces\s+people understand\./, 'keeps the approved headline');
assert.match(renderedText, /I work with teams to simplify complex workflows, design scalable interfaces, and ship polished product experiences\./, 'keeps the approved supporting copy');
assert.match(html, /View Selected Work/, 'provides the work CTA');
assert.match(html, /Start a Project/, 'provides the project CTA');
assert.match(html, /Hero illustrations svg\/mess\.svg/, 'uses the exported messy-input scene');
assert.match(html, /Hero illustrations svg\/conveyor\.svg/, 'uses the exported conveyor scene');
assert.match(html, /prefers-reduced-motion:\s*reduce/, 'respects reduced-motion preferences');
assert.doesNotMatch(renderedText, /Worked across\s+Zacks Investment Research, PeopleHum, Cosoot, and Zenskar\./, 'keeps the client list out of the hero');
assert.match(html, /class="brands-strip"/, 'adds a dedicated brands section after the hero');
assert.match(html, /padding:clamp\(58px,7vw,96px\) 0 clamp\(32px,4vw,56px\)/, 'keeps the brands-to-work transition compact');
assert.match(html, /\.page\{height:100svh;min-height:720px/, 'sizes the desktop hero to fit the first viewport');
assert.match(html, /class="brands-marquee"/, 'wraps the brands in a ticker viewport');
assert.match(html, /@keyframes brands-ticker/, 'defines the continuous ticker animation');
assert.match(html, /brand-logo--zenskar img\{width:75%/, 'reduces the Zenskar logo to 75% scale');
assert.match(renderedText, /Worked with teams across/, 'labels the brands section');
assert.match(html, /Brands SVG\/Zenskar\.svg/, 'renders the supplied Zenskar logo');
assert.match(html, /Brands SVG\/Cosoot\.svg/, 'renders the supplied Cosoot logo');
assert.match(html, /Brands SVG\/peopleHum Logo\.svg/, 'renders the supplied peopleHum logo');
assert.match(html, /Brands SVG\/Zacks\.svg/, 'renders the supplied Zacks logo');
assert.match(html, /class="featured-work-section" id="work"/, 'adds the featured work section at the work anchor');
assert.match(renderedText, /Featured work/, 'uses one featured work heading');
assert.match(html, /<h2 class="visually-hidden" id="featured-work-title">Featured work<\/h2>/, 'keeps a semantic Featured Work heading');
assert.match(html, /class="featured-work-header__art" src="\.\.\/featured-work-header-1\.svg" alt="" aria-hidden="true"/, 'uses the supplied header artwork without duplicate announcements');
assert.match(html, /\.featured-work-header__art\{display:block;width:min\(392px,calc\(100vw - 40px\)\);height:auto\}/, 'preserves the responsive 392 by 60 header artwork');
assert.match(featuredWorkHeaderSvg, /@keyframes featured-work-icon-spin/, 'defines a seamless icon rotation');
assert.match(featuredWorkHeaderSvg, /animation:featured-work-icon-spin 8s linear infinite/, 'rotates the icon slowly and continuously');
assert.match(featuredWorkHeaderSvg, /rotate\(360deg\)/, 'completes a full icon rotation without a reset jump');
assert.match(featuredWorkHeaderSvg, /@media \(prefers-reduced-motion:reduce\)/, 'provides a static reduced-motion fallback for the icon');
assert.match(html, /padding:clamp\(48px,5vw,72px\) clamp\(22px,5vw,76px\)/, 'reduces the top gap before featured work');
assert.match(html, /top:-120px;bottom:-36px;left:-160px;width:calc\(100vw \+ 160px\)/, 'masks card artwork across the full sticky-heading reveal area');
assert.match(html, /mask-image:linear-gradient\(to bottom,#000 0,#000 calc\(100% - 48px\),transparent 100%\)/, 'feathers the lower edge of the sticky work-header mask itself');
assert.match(html, /featured-work-header\{position:sticky/, 'keeps the featured-work heading sticky on desktop');
assert.match(html, /\.work-card\{position:relative;display:block;width:min\(74\.8vw,1275px\)/, 'scales desktop cards to 85 percent while keeping them centered');
assert.match(html, /\.work-card__artwork\{position:relative;display:block;width:100%;aspect-ratio:1920\/880;overflow:hidden\}/, 'crops the exported full-frame SVG to the card artwork');
assert.match(html, /transform:translateY\(-12\.96%\)/, 'hides the duplicate SVG heading above the card artwork');
assert.match(html, /Featured work sections\/work-card-01-zacks\.svg/, 'uses the Zacks exported work card');
assert.match(html, /Featured work sections\/work-card-02-peoplehum\.svg/, 'uses the peopleHum exported work card');
assert.match(html, /Featured work sections\/work-card-03-cosoot\.svg/, 'uses the Cosoot exported work card');
assert.match(html, /Featured work sections\/work-card-04-zenskar\.svg/, 'uses the Zenskar exported work card');
assert.match(html, /Scroll animation\/card_preview\.svg/, 'layers the Zacks preview artwork for scroll motion');
assert.match(html, /Scroll animation\/card_number_badge\.svg/, 'layers the Zacks number badge for scroll motion');
assert.match(html, /Scroll animation\/card_content\.svg/, 'layers the Zacks content artwork for scroll motion');
assert.match(html, /Scroll animation\/card_decorations\.svg/, 'layers the Zacks decorations for scroll motion');
assert.match(html, /class="work-card__layer work-card__layer--preview"/, 'marks the preview as an independently animated layer');
assert.doesNotMatch(html, /work-card__layer-mask/, 'does not place flat cream cover fills over the card');
assert.match(html, /Scroll animation\/card_base\.svg/, 'uses a clean base artwork without animated content baked into it');
assert.doesNotMatch(html, /mask-image:url\("data:image\/svg\+xml/, 'does not create visible rectangular cutouts over the card');
assert.match(html, /--reveal-edge:100%/, 'starts the Zacks preview reveal at its right edge');
assert.match(html, /--reveal-feather:6%/, 'gives the Zacks preview a proportional feather width');
assert.match(html, /mask-image:linear-gradient\(to right,transparent 0,transparent calc\(var\(--reveal-edge\) - var\(--reveal-feather\)\)/, 'uses a moving gradient mask instead of a hard reveal edge');
assert.match(html, /clipPath: 'inset\(0 62\.6% 0 37\.3%\)'/, 'starts the blue tape at its actual center rather than the full SVG canvas center');
assert.match(html, /gsap\.set\(badge, \{ autoAlpha: 1, scale: \.8, rotation: 3 \}\)/, 'keeps the project badge visible from its reduced reference size');
assert.match(html, /\.to\(badge, \{ scale: 1, rotation: 0/, 'grows the visible project badge from 80 to 100 percent');
assert.doesNotMatch(html, /gsap\.set\(master, \{ opacity: \.3/, 'does not expose a dim duplicate master behind the animated layers');
assert.match(html, /ScrollTrigger\.min\.js/, 'loads GSAP ScrollTrigger for the Featured Work pilot');
assert.match(html, /function initZacksWorkCardMotion\(\)/, 'scopes the Zacks card scroll animation');
assert.match(html, /function initWorkCardScaleMotion\(\)/, 'shares one entry and exit scale pattern across every work card');
assert.match(html, /function initWorkCardThumbnailMotion\(\)/, 'shares the Zacks-style thumbnail reveal with the remaining cards');
assert.match(html, /Scroll animation\/card_base_peoplehum\.svg/, 'uses a thumbnail-free PeopleHum base');
assert.match(html, /Scroll animation\/card_base_cosoot\.svg/, 'uses a thumbnail-free Cosoot base');
assert.match(html, /Scroll animation\/card_base_zenskar\.svg/, 'uses a thumbnail-free Zenskar base');
assert.match(html, /work-card__thumbnail-layer/g, 'adds isolated thumbnail reveal layers');
assert.match(html, /work-card__content-layer/g, 'adds isolated content reveal layers');
assert.match(html, /Scroll animation\/card_content_peoplehum\.svg/, 'uses a transparent PeopleHum content layer');
assert.match(html, /Scroll animation\/card_content_cosoot\.svg/, 'uses a transparent Cosoot content layer');
assert.match(html, /Scroll animation\/card_content_zenskar\.svg/, 'uses a transparent Zenskar content layer');
assert.doesNotMatch(html, /work-card--(?:peoplehum|cosoot|zenskar) \.work-card__content-layer\{clip-path:/, 'does not crop the content layers');
assert.match(html, /Scroll animation\/card_decoration_peoplehum\.svg/, 'isolates the PeopleHum decorative clip');
assert.match(html, /Scroll animation\/card_decoration_cosoot\.svg/, 'isolates the Cosoot decorative clip');
assert.match(html, /Scroll animation\/card_decoration_zenskar\.svg/, 'isolates the Zenskar decorative clip');
assert.match(html, /class="work-card__decoration-motion"/g, 'wraps each decorative clip for independent movement');
assert.match(html, /cardSelector: '\.work-card--peoplehum'/, 'configures the PeopleHum thumbnail reveal');
assert.match(html, /cardSelector: '\.work-card--cosoot'/, 'configures the Cosoot thumbnail reveal');
assert.match(html, /cardSelector: '\.work-card--zenskar'/, 'configures the Zenskar thumbnail reveal');
assert.match(html, /clipPath: config\.boundsClip, webkitClipPath: config\.boundsClip/, 'keeps each thumbnail constrained to its authored card region');
assert.match(html, /'--reveal-edge': config\.revealStart/, 'starts every thumbnail mask at its right edge');
assert.match(html, /'--reveal-edge': config\.revealEnd/, 'moves every feathered reveal from right to left');
assert.match(html, /gsap\.set\(content, \{ autoAlpha: 0, y: 32 \}\)/, 'matches the Zacks content starting state');
assert.match(html, /\.to\(content, \{ autoAlpha: 1, y: 0, duration: \.44, ease: 'power2\.out' \}, \.3\)/, 'matches the Zacks content reveal timing and movement');
assert.match(html, /gsap\.set\(decoration, \{ autoAlpha: 0, x: config\.decorationX, y: config\.decorationY, scale: \.86, rotation: config\.decorationRotation, transformOrigin: config\.decorationOrigin \}\)/, 'starts each decorative clip invisibly within its visible runway');
assert.match(html, /autoAlpha: 1,\s+x: config\.overshootX,\s+y: config\.overshootY,\s+scale: 1\.035,\s+rotation: config\.overshootRotation/, 'fades and travels each decorative clip through a small overshoot');
assert.match(html, /duration: \.5,\s+ease: 'power3\.out'/, 'uses a decelerating approach rather than an abrupt edge crossing');
assert.match(html, /\.to\(decoration, \{ x: 0, y: 0, scale: 1, rotation: 0, duration: \.18, ease: 'back\.out\(1\.15\)' \}, \.48\)/, 'settles each decorative clip into its authored position');
assert.match(html, /document\.querySelectorAll\('\.featured-work-cards \.work-card'\)/, 'targets all four featured-work cards');
assert.match(html, /start:\s*'top 92%'/, 'begins each incoming card scale near the lower viewport edge');
assert.match(html, /end:\s*'bottom 8%'/, 'continues each card scale until it leaves the upper viewport area');
assert.match(html, /scale:\s*\.8,\s*transformOrigin:\s*'50% 50%'/, 'starts every incoming card at eighty percent');
assert.match(html, /\.to\(card, \{ scale: 1, duration: \.42/, 'grows incoming cards to full scale');
assert.match(html, /\.to\(card, \{ scale: \.8, duration: \.4/, 'reduces outgoing cards back to eighty percent');
assert.match(html, /start:\s*'top 85%'/, 'starts the Zacks build as it enters the viewport');
assert.match(html, /end:\s*'center center'/, 'finishes the Zacks build near the viewport center');
assert.match(html, /scrub:\s*\.8/, 'scrubs the Zacks build smoothly with scrolling');
assert.match(html, /max-width:\s*700px/, 'uses a static Zacks card on small screens');
assert.match(html, /href="\/work\/zacks-insights"/, 'links the Zacks card to its case study route');
assert.match(html, /href="\/work\/peoplehum"/, 'links the peopleHum card to its case study route');
assert.match(html, /href="\/work\/cosoot-sustainability"/, 'links the Cosoot card to its case study route');
assert.match(html, /href="\/work\/zenskar"/, 'links the Zenskar card to its case study route');
assert.match(html, /gsap\.min\.js/, 'loads the local GSAP runtime');
assert.match(html, /id="stage_01_messy_inputs"/, 'provides a target for the messy-input stage');
assert.match(html, /id="stage_02_map_board"/, 'provides a target for the mapping stage');
assert.match(html, /id="stage_03_lowfi_screen"/, 'provides a target for the low-fi stage');
assert.match(html, /id="stage_04_hifi_dashboard"/, 'provides a target for the dashboard stage');
assert.match(html, /id="conveyor_belt_group"/, 'provides a target for the conveyor');
assert.match(html, /class="lamp-bulb"/, 'marks lamps for sequential illumination');
assert.match(html, /Hero illustrations svg\/lamp\.svg/, 'uses the supplied illustrated lamp asset');
assert.match(html, /gsap\.timeline\(/, 'uses a GSAP load timeline');
assert.match(html, /class="screen-outline"/, 'includes an outline construction pass for the screens');
assert.match(html, /function prepareDrawLines\(stageSelector\)/, 'prepares SVG strokes for construction');
assert.match(html, /function getBottomToTopElements\(stageSelector\)/, 'orders construction from bottom to top');
assert.match(html, /function animateStage\(tl, config\)/, 'builds each station in sequence');
assert.match(html, /function animateMessyInput\(tl\)/, 'isolates the first station construction pass');
assert.match(html, /const messyLines = createMessySketchLines\(\)/, 'draws the messy-input overlay before revealing its color layer');
assert.match(html, /function prepareSketchLines\(lines\)/, 'prepares the isolated sketch paths for drawing');
assert.match(html, /\.to\(`\$\{stage\} \.stage-fills`, \{ autoAlpha: 1/, 'resolves each colored station after its strokes');
assert.match(html, /gsap\.set\('\.screen-outline', \{ autoAlpha: 0 \}\)/, 'keeps static stations from rendering their duplicate outline layer');
assert.match(html, /overlayId: 'messy-sketch-overlay'/, 'creates a dedicated line overlay for the messy-input station');
assert.match(html, /cloneNode\(true\)/, 'draws cloned sketch paths independently from the master illustration');
assert.match(html, /minY: 85/, 'excludes the overhead lamp from the messy-input sketch overlay');
assert.match(html, /\.to\(lines, \{ autoAlpha: 0, duration: \.18/, 'removes each temporary sketch as its finished artwork resolves');
assert.match(html, /function createStageSketchLines\(config\)/, 'creates an isolated sketch overlay for each station');
assert.match(html, /function animateSketchStage\(tl, stage, lines\)/, 'applies the sketch-to-artwork handoff to every station');
assert.match(html, /animateSketchStage\(timeline, '#stage_02_map_board', mapLines\)/, 'animates the map station after the messy-input station');
assert.match(html, /animateSketchStage\(timeline, '#stage_03_lowfi_screen', lowfiLines\)/, 'animates the low-fi station after the map station');
assert.match(html, /animateSketchStage\(timeline, '#stage_04_hifi_dashboard', hifiLines\)/, 'animates the dashboard after the low-fi station');
assert.match(html, /excludeRects: \[\{ minX: 890, maxX: 960, minY: 230, maxY: 420 \}\]/, 'keeps the first control pillar out of the map sketch overlay');
assert.match(html, /excludeRects: \[\{ minX: 1315, maxX: 1390, minY: 230, maxY: 420 \}\]/, 'keeps the second control pillar out of the low-fi sketch overlay');
assert.match(html, /!config\.excludeRects\?\.some/, 'filters excluded static scene regions before cloning sketch paths');
assert.match(html, /excludePaths: \['M706\.517 163\.204V195\.847'\]/, 'removes the unwanted top connector from the map sketch overlay');
assert.match(html, /!config\.excludePaths\?\.includes\(element\.getAttribute\('d'\)\)/, 'filters excluded connector paths before cloning');
assert.match(html, /id="outline-illustration"/, 'inlines the supplied full illustration outline');
assert.match(html, /strokeDashoffset/, 'draws SVG strokes with dash offsets');
assert.match(html, /matchMedia\('\(prefers-reduced-motion: reduce\)'\)/, 'uses JavaScript reduced-motion handling');
assert.match(html, /family=Manrope/, 'loads Manrope as the body font');
assert.doesNotMatch(html, /Plus Jakarta Sans/, 'does not retain Plus Jakarta Sans');
assert.match(html, /class="page-scroll-progress"/, 'adds a fixed page scroll progress indicator');
assert.match(html, /role="progressbar"/, 'exposes scroll progress semantics to assistive technology');
assert.match(html, /class="page-scroll-progress__bar"/, 'provides a transform-driven progress fill');
assert.match(html, /function initPageScrollProgress\(\)/, 'initializes page scroll progress without React');
assert.match(html, /requestAnimationFrame\(update\)/, 'batches progress updates with the browser paint cycle');
assert.match(html, /aria-valuenow/, 'keeps the accessible progress value current');
assert.doesNotMatch(html, /initHeroHeadlineTextEffect|headline-char/, 'keeps the hero headline static beside the animated illustration');

console.log('Interface Workshop hero acceptance checks passed.');
