import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../outputs/interface-workshop-hero.html', import.meta.url), 'utf8');
const renderedText = html.replace(/<[^>]+>/g, ' ');

assert.match(html, /<nav[\s>]/, 'provides semantic navigation');
assert.match(renderedText, /I shape messy product ideas into\s+interfaces\s+people understand\./, 'keeps the approved headline');
assert.match(renderedText, /I help SaaS, fintech, and growing teams simplify workflows, redesign dashboards, and build polished digital experiences\./, 'keeps the approved supporting copy');
assert.match(html, /View Selected Work/, 'provides the work CTA');
assert.match(html, /Start a Project/, 'provides the project CTA');
assert.match(html, /Hero illustrations svg\/mess\.svg/, 'uses the exported messy-input scene');
assert.match(html, /Hero illustrations svg\/conveyor\.svg/, 'uses the exported conveyor scene');
assert.match(html, /prefers-reduced-motion:\s*reduce/, 'respects reduced-motion preferences');
assert.match(renderedText, /Worked across\s+Zacks Investment Research, PeopleHum, Cosoot, and Zenskar\./, 'includes the approved trust line');
assert.match(html, /gsap\.min\.js/, 'loads the local GSAP runtime');
assert.match(html, /id="stage_01_messy_inputs"/, 'provides a target for the messy-input stage');
assert.match(html, /id="stage_02_map_board"/, 'provides a target for the mapping stage');
assert.match(html, /id="stage_03_lowfi_screen"/, 'provides a target for the low-fi stage');
assert.match(html, /id="stage_04_hifi_dashboard"/, 'provides a target for the dashboard stage');
assert.match(html, /id="conveyor_belt_group"/, 'provides a target for the conveyor');
assert.match(html, /class="lamp-bulb"/, 'marks lamps for sequential illumination');
assert.match(html, /Hero illustrations svg\/lamp\.svg/, 'uses the supplied illustrated lamp asset');
assert.match(html, /gsap\.timeline\(/, 'uses a GSAP load timeline');
assert.match(html, /class="screen-outline"/, 'includes an outline construction pass for the screens');
assert.match(html, /function prepareDrawLines\(stageSelector\)/, 'prepares SVG strokes for construction');
assert.match(html, /function getBottomToTopElements\(stageSelector\)/, 'orders construction from bottom to top');
assert.match(html, /function animateStage\(tl, config\)/, 'builds each station in sequence');
assert.match(html, /function animateMessyInput\(tl\)/, 'isolates the first station construction pass');
assert.match(html, /const messyLines = createMessySketchLines\(\)/, 'draws the messy-input overlay before revealing its color layer');
assert.match(html, /function prepareSketchLines\(lines\)/, 'prepares the isolated sketch paths for drawing');
assert.match(html, /\.to\(`\$\{stage\} \.stage-fills`, \{ autoAlpha: 1/, 'resolves each colored station after its strokes');
assert.match(html, /gsap\.set\('\.screen-outline', \{ autoAlpha: 0 \}\)/, 'keeps static stations from rendering their duplicate outline layer');
assert.match(html, /overlayId: 'messy-sketch-overlay'/, 'creates a dedicated line overlay for the messy-input station');
assert.match(html, /cloneNode\(true\)/, 'draws cloned sketch paths independently from the master illustration');
assert.match(html, /minY: 85/, 'excludes the overhead lamp from the messy-input sketch overlay');
assert.match(html, /\.to\(lines, \{ autoAlpha: 0, duration: \.18/, 'removes each temporary sketch as its finished artwork resolves');
assert.match(html, /function createStageSketchLines\(config\)/, 'creates an isolated sketch overlay for each station');
assert.match(html, /function animateSketchStage\(tl, stage, lines\)/, 'applies the sketch-to-artwork handoff to every station');
assert.match(html, /animateSketchStage\(timeline, '#stage_02_map_board', mapLines\)/, 'animates the map station after the messy-input station');
assert.match(html, /animateSketchStage\(timeline, '#stage_03_lowfi_screen', lowfiLines\)/, 'animates the low-fi station after the map station');
assert.match(html, /animateSketchStage\(timeline, '#stage_04_hifi_dashboard', hifiLines\)/, 'animates the dashboard after the low-fi station');
assert.match(html, /excludeRects: \[\{ minX: 890, maxX: 960, minY: 230, maxY: 420 \}\]/, 'keeps the first control pillar out of the map sketch overlay');
assert.match(html, /excludeRects: \[\{ minX: 1315, maxX: 1390, minY: 230, maxY: 420 \}\]/, 'keeps the second control pillar out of the low-fi sketch overlay');
assert.match(html, /!config\.excludeRects\?\.some/, 'filters excluded static scene regions before cloning sketch paths');
assert.match(html, /excludePaths: \['M706\.517 163\.204V195\.847'\]/, 'removes the unwanted top connector from the map sketch overlay');
assert.match(html, /!config\.excludePaths\?\.includes\(element\.getAttribute\('d'\)\)/, 'filters excluded connector paths before cloning');
assert.match(html, /id="outline-illustration"/, 'inlines the supplied full illustration outline');
assert.match(html, /strokeDashoffset/, 'draws SVG strokes with dash offsets');
assert.match(html, /matchMedia\('\(prefers-reduced-motion: reduce\)'\)/, 'uses JavaScript reduced-motion handling');
assert.match(html, /family=Manrope/, 'loads Manrope as the body font');
assert.doesNotMatch(html, /Plus Jakarta Sans/, 'does not retain Plus Jakarta Sans');

console.log('Interface Workshop hero acceptance checks passed.');
